spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
graphql:
  servlet:
    corsEnabled: true
    subscriptions:
      websocket:
        path: /subscriptions
logging:
  level:
    root: info